import type { ThemeColors } from '../types';

export const themes: ThemeColors[] = [
  {
    id: 'cream',
    name: 'Crema',
    bg: '#FFF8F0',
    bgSecondary: '#FEF0E1',
    bgCard: '#FFFFFF',
    text: '#4A3728',
    textSecondary: '#8B7355',
    accent: '#D4956A',
    accentLight: '#F0D5BE',
    border: '#E8D5C4',
    checkboxBg: '#F5E6D3',
    checkboxChecked: '#9BBF8A',
    danger: '#D98E8E',
    sectionHeaderBg: '#FEF5EC',
  },
  {
    id: 'lavender',
    name: 'Lavanda',
    bg: '#F5F0FF',
    bgSecondary: '#EDE4FF',
    bgCard: '#FFFFFF',
    text: '#3D2E5C',
    textSecondary: '#7B6B99',
    accent: '#9B7ED8',
    accentLight: '#D4C4F0',
    border: '#DDD0F0',
    checkboxBg: '#EDE4FF',
    checkboxChecked: '#9BBF8A',
    danger: '#D98E8E',
    sectionHeaderBg: '#F0EAFF',
  },
  {
    id: 'mint',
    name: 'Menta',
    bg: '#F0FFF4',
    bgSecondary: '#E0F5E8',
    bgCard: '#FFFFFF',
    text: '#2D4A37',
    textSecondary: '#5C8A6E',
    accent: '#6BBF8A',
    accentLight: '#B8E6CC',
    border: '#C8E6D4',
    checkboxBg: '#E0F5E8',
    checkboxChecked: '#6BBF8A',
    danger: '#D98E8E',
    sectionHeaderBg: '#E8F8EE',
  },
  {
    id: 'rose',
    name: 'Rosa',
    bg: '#FFF0F3',
    bgSecondary: '#FFE0E6',
    bgCard: '#FFFFFF',
    text: '#4A2832',
    textSecondary: '#996070',
    accent: '#D97B8F',
    accentLight: '#F0C4CF',
    border: '#F0D0D8',
    checkboxBg: '#FFE0E6',
    checkboxChecked: '#9BBF8A',
    danger: '#D94050',
    sectionHeaderBg: '#FFF0F3',
  },
  {
    id: 'ocean',
    name: 'Oceano',
    bg: '#F0F7FF',
    bgSecondary: '#E0EDFF',
    bgCard: '#FFFFFF',
    text: '#283D5C',
    textSecondary: '#607099',
    accent: '#5B8ED9',
    accentLight: '#B8D0F0',
    border: '#C8D8F0',
    checkboxBg: '#E0EDFF',
    checkboxChecked: '#9BBF8A',
    danger: '#D98E8E',
    sectionHeaderBg: '#EAF2FF',
  },
  {
    id: 'dark',
    name: 'Oscuro',
    bg: '#1A1A2E',
    bgSecondary: '#16213E',
    bgCard: '#222244',
    text: '#E0E0F0',
    textSecondary: '#A0A0C0',
    accent: '#7B68EE',
    accentLight: '#3D3570',
    border: '#333366',
    checkboxBg: '#2A2A4A',
    checkboxChecked: '#6BBF8A',
    danger: '#FF6B6B',
    sectionHeaderBg: '#252550',
  },
];

export function getThemeById(
  id: string,
  customThemes: ThemeColors[] = []
): ThemeColors {
  const all = [...themes, ...customThemes];
  return all.find((t) => t.id === id) || themes[0];
}
